name: D365 Solution CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      solution-name:
        description: "Enter the D365 Solution Name"
        required: true
        type: string

jobs:
  build:
    name: Build D365 Solution
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Power Platform Auth
        uses: microsoft/powerplatform-actions/authenticate@v1.8.0
        with:
          client-id: ${{ secrets.D365_CLIENT_ID }}
          client-secret: ${{ secrets.D365_CLIENT_SECRET }}
          tenant-id: ${{ secrets.D365_TENANT_ID }}
          environment-url: ${{ secrets.D365_URL }}

      - name: Export Unmanaged Solution
        uses: microsoft/powerplatform-actions/export-solution@v1.8.0
        with:
          environment-url: ${{ secrets.D365_URL }}
          solution-name: ${{ inputs.solution-name }}
          solution-output-file: ./artifacts/${{ inputs.solution-name }}.zip
          managed: false  # Export as unmanaged

      - name: Upload Solution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: d365-solution
          path: ./artifacts/${{ inputs.solution-name }}.zip

  deploy-uat:
    name: Deploy to UAT
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment-url: ${{ secrets.D365_URL }}
      solution-name: ${{ inputs.solution-name }}
      solution-file: d365-solution
      managed: true

  deploy-prod:
    name: Deploy to Production
    needs: deploy-uat
    uses: ./.github/workflows/deploy.yml
    with:
      environment-url: ${{ secrets.D365_URL }}
      solution-name: ${{ inputs.solution-name }}
      solution-file: d365-solution
      managed: true
